  name: bluebuild
on:
  schedule:
    - cron: "00 06 * * *"
  push:
    paths-ignore:
      - "**.md"
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  bluebuild:
    name: Build Custom Image & ISO
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        recipe:
          - recipe.yml
    steps:
      - name: Build Custom Image
        uses: blue-build/github-action@v1.11
        with:
          recipe: ${{ matrix.recipe }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}
          build_opts: "--no-sign"
          maximize_build_space: true

  generate-iso:
    name: Generate Installer ISO
    needs: bluebuild
    runs-on: ubuntu-latest
    steps:
      - name: Generate ISO
        uses: jasonn3/build-container-installer@v1.2.2
        with:
          image_name: fedora-ultimate-gaming
          image_repo: ghcr.io/${{ github.repository_owner }}
          version: latest
          variant: Kde

      - name: Upload ISO Artifact
        uses: actions/upload-artifact@v4
        with:
          name: fedora-ultimate-gaming-installer-iso
          path: "*.iso"
       
